### ISSUE TITLE
[CLI] Payment Status

### ISSUE THREAD

**Issue by prekucki** [golemfactory/yagna#139]
Expected:

```yagna payment status```

```yaml
---
amount: 100 GNT
reserved: 0 GNT
outgoing:
   requested: 0 GNT
   accepted: 0 GNT
   confirmed: 0 GNT
   rejected: 0 GNT
incoming:
   requested: 0 GNT
   accepted: 0 GNT
   confirmed: 0 GNT
   rejected: 0 GNT
```
