### ISSUE TITLE
Why office Providers don't send Offers

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#2163]
What:
We weren't able to compute on office Providers.
It seems we didn't get any Proposal from them

**Comment by wkargul** [comment]
We didn't get any proposals from office Providers as their hardware configuration is as follows:
```yaml
ya_provider_hardware:
  cpu_threads: 1
  mem_gib: 4
  storage_gib: 20
```

therefore when we run `start_stop_blender.py` with default parameters as `min_cpu_threads = 2`, `min_mem_gib = 0.5` and `min_storage_gib=2.0` we automatically had all the office providers outside the circle.

Our hybrid nodes configuration:

```yaml
#OFFICE
ya_provider_hardware:
  cpu_threads: 1
  mem_gib: 4
  storage_gib: 20

#OVH BAREMETAL
ya_provider_hardware:
  cpu_threads: 2
  mem_gib: 8
  storage_gib: 100

#OPENSTACK
ya_provider_hardware:
   cpu_threads: 1
   mem_gib: 1.2881845235824585
   storage_gib: 17.557345581054687
   ```

I have prepared some variations and I was able to compute on nodes either from office, ovh or opestack so the issue is not valid anymore.
